### ISSUE TITLE
[1.19.3] Config options for slot rendering & a UI button to open them

### ISSUE THREAD

**Issue by vizthex123** [emilyploszaj/trinkets#229] opened 2022-12-24 06:38 UTC
It's kind of annoying how the gloves slot is always on-screen. I'd much rather have a button to open the UI like Baubles and Curio do, but noticed there isn't a config for the mod.

Would be great if one got added.

**Comment by emilyploszaj** [comment] 2024-02-22 04:12
Duplicate of #157

**Closed by emilyploszaj** 2024-02-22 04:12 UTC
